### ISSUE TITLE
UDP ?

### ISSUE THREAD

**Issue by dagnall53** [norbert-walter/Windsensor_Yachta#1] opened 2024-03-21 11:35 UTC
I am trying to assist a user of your wifi Anemometer to connect into a boat network using a NMEA4WIFI multiplexer.
He will connect to the Multiplexer AP, (and will also connect a PC/Tablet (+openCPN) to this AP.)

It is not appropriate in this situation to use TCP for the anemometer<>multiplexer link, as the Multiplexer can only support a single TCP link, thus preventing the PC<>multiplexer from using TCP. 

A better approach is to use UDP (broadcast) from the anemometer, as this data can then be "seen" both by the multiplexer and also by the Tablet/Pc that is also connected to the Multiplexer AP. 

Open CPN has the facility to accept multiple  "connections" and I have confirmed with practical simulations that an Anemometer could (eg) send nmea0183 on UDP port 8080, and the Multiplexer can send (eg AIS etc) on UDP port 2000.   

However, looking at the source code, I could not see any UDP transmission.  Is this hidden? or missing?
If Missing, is there a version of the software that offers UDP transmission options?

**Comment by norbert-walter** [comment] 2024-03-21 13:27
Hello,

Thank you for your interest in the Yachta wind sensor. The firmware only supports a TCP connection. The wind sensor is the TCP server and a client can connect to the server. UDP is not supported because it clutters up the network. UDP is usually transmitted as a broadcast message and all participants in the network have to evaluate the UDP telegrams, which ties up considerable resources.
   
What for a system is the destination for all transmissions? If you using OpenCPN you can connect the wind sensor with a second TCP connection. That is possible. You don't need to using the multiplexer for the wind sensor data.

The source code is open and you are welcome to add a UDP transmission. You can find the current source code here: 

https://github.com/norbert-walter/Windsensor_Yachta

Norbert

**Comment by dagnall53** [comment] 2024-03-21 16:44
Thanks. 
My correspondent is French, so we may have had some (google) translate errors. 
He has now advised that he is unable to connect to the NMEA4WIFI multiplexer Access Point, and I now think this may be due to differences in terminology (client / external network/  access point ). 

He is trying to get the Anemometer to connect to the WIFI Access Point created by the NMEA4WIFI. (this is password protected).  A laptop, phone and other devices will also connect to the NMEA4WIFI Access point.

He can then multiplex the data from a number of NMEA0183 sources and make this available from the NMEA4WIFI. To make the data simultaneously available on (eg)  Navionics on phone and OpenCPN on PC, it is most suitable to use UDP.  TCP would only be available to one or device at a time.   

Looking at your source I think you can allow the anemometer to connect to an existing external WIFI network, and you appear to call this a "WLAN CLIENT" in your setup? 
My correspondent sent me a screen capture of the anemometer setup, which appears to show "WLAN CLIENT", where he can enter "NMEA4WIFI"  but no field to add password ?? . 
Can you paste a photo of the settings needed to connect to an existing WIFI network with the ssid "NMEA4WIFI", AND password "12345678" ?  It would assist greatly!

This is the image he sent us. 
![IMG_20240317_153300](https://github.com/norbert-walter/Windsensor_Yachta/assets/6950560/84eab2bb-e6c4-4393-950e-185f3a18161a)

**Comment by norbert-walter** [comment] 2024-03-21 18:25
Okay I understand. The wind sensor should be part of the WiFi network of NMEA4WIFI multiplexer and send data to the device. You can also do this with TCP and the NMEA4WiFI. If the multiplexer has the WiFi **SSID**: _NMEA4WIFI_ and the **password**: _12345678_, then you have to enter this connection data in the wind sensor in **Device Settings** under **WLAN Client SSID**: _NMEA4WIFI_ and **WLAN Client Password**: _12345678_. Then press the **Save** button and reboot the wind sensor. The reboot can also be achieved by briefly switching off the power on the wind sensor. After the boot, the blue LED lights up. If it is off, then the wind sensor has logged into the WiFi of the multiplexer. You should then see an IP address under **WLAN Clinet IP**. With the multiplexer you have to proceed as described here (TCP Port for Receiving).

https://www.vela-navega.com/nmea4wifi/docs/nmea4wifi_files/RxTCP.html

The IP address must be the IP address of the wind sensor. For the **port** you use _6666_. As soon as the multiplexer has connected to the wind sensor, the wind sensor sends data to the multiplexer. The blue LED flashes every time data is transferred. This is also how it works with a TCP transmission with the multiplexer. Please give me feedback if it worked.

**Comment by dagnall53** [comment] 2024-03-21 18:53
Many thanks,
I will pass this on, but I have simulated with an esp8266 this afternoon, and although I managed to get the WiFi 1000 to connect to the NMEA4 (which I helped write) , 
![Screenshot 2024-03-21 184833](https://github.com/norbert-walter/Windsensor_Yachta/assets/6950560/46a0eb04-8499-46b9-972b-a45f3535ff6e)
but I could not see TCP data recieved on NMEA4, and it was then not possible to connect to the 192.168.4.23 for your websettings. (although I was still able to connect to your AP and use 192.168.4.1 ) 
I presumed these settings would send (TCP) (port 6666) to the NMEA4WIFI, which is at 192.168.4.1 ? 
![image](https://github.com/norbert-walter/Windsensor_Yachta/assets/6950560/a38f8bf9-36ac-4163-92a5-0d44bd4b77ca)

**Comment by dagnall53** [comment] 2024-03-21 18:57
The trouble with TCP is that all the IP addresses need to be specified!!  I suspect you are sending to a different address to the NMEA4's 192.168.4.1 ?   
;-) UDP broadcast is (generally!) so much simpler!!  
;-)

**Comment by norbert-walter** [comment] 2024-03-21 19:14
The problem is both WiFi network use the same network addresses 192.168.4.X. It is a routing problem. We need to separate the networks with different network addresses. At the moment I can't change the network basis address via Web configuration. It is hard coded in the firmware and the same as by NMEA4WIFI.

As a quick solution I compile a special version for you with a different network address. I think then is it working.

**Comment by norbert-walter** [comment] 2024-03-21 20:19
Please use this firmware V1.19. I changed the network address from wind sensor to 192.168.5.1

Unzip the file and make a firmware update.
[firmware.bin.zip](https://github.com/norbert-walter/Windsensor_Yachta/files/14706703/firmware.bin.zip)

If you want to test at home you can use in the configuration the **Serve Mode**: _Demo Mode_. The the device simulate wind sensor data and you can check the data transmission.

**Comment by dagnall53** [comment] 2024-03-22 10:49
Hi,
I got Update error: *ERROR[4]: Not Enough Space when trying via the WIFI*,
when trying to OTA via WIFI , but the NodeFlash software over serial worked
fine. (I had forgotten about that software!)
FYI, Luis, who has been following this thread, notes I missed that the
NMEA4 and your device are BOTH servers, and so the NMEA4 will not be able
to (see/) connect to the Anemometer. BUT that does not stop Open CPN from
seeing the anemometer!.

I *was *able to connect this PC and the anemometer to a NMEA4WIFI. The
NMEA4WIFI gave the Anemometer the IP 192.168.4.2 , and that was enough to
allow OpenCPN to have two connections open. (192.168.4.1 udp 2000 is
simulated AIS) and (192.168.4.2 TCP 6666 for your anemometer). I like to
capture images.. and proves it works (at least once ;-) )
[image: image.png]
Many thanks. I will pass this on to my correspondent.

Th only complication is that we (NMEA4) may not always allocate the
anemometer the ip 192.168.4.2 every time, depending on the connection (PC
first or anemometer first ) sequence!  I will have a chat to Luis and see
what he thinks.
I think the user can still connect to "NoWa" using a separate device to
check the allocated IP. and this may be the most practical solution to find
the Anemometer IP after it connects..

Many thanks
Dagnall

**Comment by norbert-walter** [comment] 2024-03-22 10:59
Hi Dagnall,

Fine, I'm happy.

With the IP addresses you can also using a host name. The wind sensor supports mDNS with the name: _windsensor-0.local_ or a normal host name as: _windsensor-0_
You can try to use the names in the multiplexer NMEA4WIFI. Then is it undependent from the IP address. In AVnav and OpenCPN or other software is it working.

For a firmware update you can using the webpage **Update**. With a manual update over a file *.bin or *.wsb is it also working. Direct OTA via Arduino IDE is not working. 

For the future I want to change the network address to 192.168.5.1 for the wind sensor in the new firmware version V1.20. In this case we reduce the problems with other ESP32 or ESP8266 equipment and standard network addresses 192.168.4.x.

Norbert

**Comment by dagnall53** [comment] 2024-03-22 11:37
Yes, it works!
Thanks,
I will also try the alternate approach .. and change our SSID AP range -
It's something I rarely do as it is quite complex via the web interface
(deliberately- to avoid users getting confused!) , but I am afraid that my
OCD now has the better of me and now I need to find if that would work as
well! .

Many thanks..
Dagnall

**Comment by dagnall53** [comment] 2024-03-22 12:55
Yes, we can also use your standard sw, and change OUR SSID IP. 
. FYI: 
its done in our code  by adding the new SSID default IP in the "name field" separated by ".."
![image](https://github.com/norbert-walter/Windsensor_Yachta/assets/6950560/2510ea8f-255a-482f-8769-abc55a6800c6)
This then works with your unmodified Anemometer software. 
Thanks for helping us to find the IP clash.
Dagnall

**Comment by norbert-walter** [comment] 2024-03-22 13:20
I solved the problem with a new firmware version V1.20. I changed the IP address from 192.168.4.1 to 192.168.5.1 If you want you can use the new firmware.

A update over Internet connection is available.

**Comment by dagnall53** [comment] 2024-03-22 14:02
out of interest, I tried to compile and run WiFi_Windsensor, but I must have the wrong AS5600 library, as I get loads of
related compile errors: I use https://github.com/RobTillaart/AS5600..
I get,, 
_Compilation error: 'AMS_5600' does not name a type; did you mean 'AS5600'?
 'class AS5600' has no member named 'getMagnitude'; did you mean 'readMagnitude'?
   84 |         magnitude = ams5600.getMagnitude();_

**Comment by norbert-walter** [comment] 2024-03-22 14:31
I use not the lib from Rob Tillaat. I use the lib from Tom Denton. The lib is included in my repository.

Please use Gitpod as software development environment: https://gitpod.io/#https://github.com/norbert-walter/Windsensor_Yachta All libs are includes and you have all components as cloud project. Try it!

Pleas refer the main page!

**Comment by norbert-walter** [comment] 2024-03-22 14:32
Fix in version V1.20

**Closed as completed by norbert-walter** 2024-03-22 14:32 UTC
Labels: bug

**Comment by dagnall53** [comment] 2024-03-22 19:14
Cannot use gitpod.  I have enough trouble with github! (I suspect I am quite a bit older than you and its a case of "old dogs and new tricks"!) sorry. But thanks for making me aware of it. 
Tom Denton AMS_5600 library ???  (EDIT: Got it(?) Seed Studio!! ) (https://github.com/Seeed-Studio/Seeed_Arduino_AS5600/blob/master/src/AS5600.h) 
I thought I had read the main page.. and found these libraries but where is the AS5600.h ? 
![image](https://github.com/norbert-walter/Windsensor_Yachta/assets/6950560/bd77aba7-56ae-4771-9489-d0540adb1be9)
Gitlab version has less data - unless I missed something?

**Comment by norbert-walter** [comment] 2024-03-22 23:26
I don't support the Github project page. I changed the project to Github. I have more possibilities with Github to integrate several technologies more. You find the lib for the As5600 direct in the file repository. Please refer the includes in main.

https://github.com/norbert-walter/Windsensor_Yachta/tree/main/src

Gitpod is very easy to use. But you need a free Github account. You don't need any software components. All runs in the web browser. You see a complete software development environment in your browser similar to PlatformIO. Please try it! It is really easy and runs out of the box without any problems. Tip from a old dog to a old dog ;-)

**Comment by dagnall53** [comment] 2024-03-23 10:17
"_**I don't support the Github project page. I changed the project to Github. I have more possibilities with Github**_ "
I think perhaps auto correct got involved?? ;-)  one of those should have been gitLAB.. (?)
I have now copied the proper Github version.. so have the AS5600.h file.. 
The subtle difference in gitlab version I had copied was as5600 was a "proper library" so in <> ! It shows how hard it is to see these small differences!
I have had some feedback from the user, and I will see if I can send you an email as its not that relevant to this thread, which can now be closed!

**Comment by norbert-walter** [comment] 2024-03-23 10:45
That was exactly the reason for me to switch from the Arduino IDE to PlatformIO. The issue of integrating the right libs is not solved satisfactorily under the Arduino IDE and causes major problems when projects with many libs are used by others. The new version 2.0 of the Arduino IDE doesn't change much. See your own questions. With PlatformIO, the correct libs are always loaded in the correct version because you can specify them precisely. Since PlatformIO is integrated as a plugin in Visual Studio Code, you end up back at Microsoft and Github. I'm not a Microsoft fan, but for me Visual Studio Code is far better at programming than the Arduino IDE, especially if you want to implement extensive software projects. GitLab also works, but the integration into VSC is not as smooth as with Guthub. With Gitpod the whole thing becomes even easier because you don't even have to install VSC and PlatformIO. Everything runs out of the box in the web browser. Simple as it gets. This saves you a lot of work and frustration when installing a software development environment and runs on any device, including your cell phone or tablet. You can use it directly anywhere in the world. Just try it! Then you can tell me what you don't like about it.

You can also flash the ESP8266 directly from the browser with a USB cable without needing any special software or installations.

**Comment by dagnall53** [comment] 2024-03-23 11:07
I sent an email, but will just close this with saying I need to explore  Visual Studio Code. I have used it for modifications for Marlin for the ender3.. but with great difficulty! 
It just does not feel at all familiar to me.
